const imageFiles=['水洗棉-三丽鸥-云朵玉桂狗.jpg','水洗棉-三丽鸥-五彩KT猫.jpg','水洗棉-三丽鸥-库罗米之心.jpg','水洗棉-三丽鸥-牛奶玉桂狗.jpg','水洗棉-中东灰+玛瑙灰.jpg','水洗棉-奶油小心心.jpg','水洗棉-奶油黄昏.jpg','水洗棉-奶粉+葡萄紫.jpg','水洗棉-奶黄格双拼.jpg','水洗棉-威斯汀.jpg','水洗棉-小草莓.jpg','水洗棉-抹茶绿+奶黄.jpg','水洗棉-散漫春色.jpg','水洗棉-时空探索-蓝.jpg','水洗棉-星星KT.jpg','水洗棉-晨曦粉蓝.jpg','水洗棉-海盐格双拼.jpg','水洗棉-爱心凯蒂.jpg','水洗棉-班迪蓝+浅蓝芝士.jpg','水洗棉-白+浅蓝.jpg','水洗棉-白+豆绿.jpg','水洗棉-白银条双拼.jpg','水洗棉-米兰.jpg','水洗棉-糖果星星人.jpg','水洗棉-莓蓝条双拼.jpg','水洗棉-菊橙条双拼.jpg','水洗棉-蓝仔小熊-蓝.jpg','水洗棉-雾蓝格双拼.jpg','水洗棉-麦田灰.jpg'];
const styles=imageFiles.map((file,index)=>({name:`花色 ${String(index+1).padStart(2,'0')}｜${file.replace(/^水洗棉-/, '').replace(/\.jpg$/, '')}`,url:encodeURI(`assets/water/${file}`)}));
const productImages={pillow:'assets/products/pillow.jpg',duvet:'assets/products/duvet.jpg',mattress:'assets/products/mattress.jpg',bundle:'assets/products/bundle.jpg',cotton:'assets/products/cotton.jpg'};
const photo=(name,url)=>({name,url});
const set=(id,name,price,deposit,cost,tier,desc,tag='')=>({id,type:'套餐',name,price,deposit,cost,tier,desc,tag,styles,photo:photo('套餐展示图',productImages.bundle)});
const single=(id,name,price,deposit,cost,tier,desc,image='')=>({id,type:'单卖',name,price,deposit,cost,tier,desc,styles:id==='T01'?styles:[photo('默认款式',image)],photo:photo('商品展示图',image)});
const products=[set('S06','水洗棉六件套｜小竹垫',428,50,169,[318,298,298,288],'奶酪枕 + 4斤奶酪被 + 水洗棉三件套 + 6CM小竹垫','引流款'),set('S07','水洗棉七件套｜小竹垫',488,50,202,[358,338,338,328],'奶酪枕 + (2+4)子母奶酪被 + 水洗棉三件套 + 6CM小竹垫'),set('S09','水洗棉九件套｜小竹垫',528,50,205,[378,358,358,348],'奶酪枕 + 4斤奶酪被 + 水洗棉三件套×2 + 6CM小竹垫','主推'),set('S10','水洗棉十件套｜小竹垫',578,50,237,[418,398,398,388],'奶酪枕 + (2+4)子母奶酪被 + 水洗棉三件套×2 + 6CM小竹垫'),set('L06','水洗棉六件套｜小蓝垫',458,50,189,[338,318,318,308],'奶酪枕 + 4斤奶酪被 + 水洗棉三件套 + 4CM小蓝垫'),set('L07','水洗棉七件套｜小蓝垫',518,50,222,[398,378,378,368],'奶酪枕 + (2+4)子母奶酪被 + 水洗棉三件套 + 4CM小蓝垫'),set('L09','水洗棉九件套｜小蓝垫',558,50,225,[418,398,398,388],'奶酪枕 + 4斤奶酪被 + 水洗棉三件套×2 + 4CM小蓝垫'),set('L10','水洗棉十件套｜小蓝垫',608,50,257,[448,428,428,418],'奶酪枕 + (2+4)子母奶酪被 + 水洗棉三件套×2 + 4CM小蓝垫'),single('P01','枕芯｜奶酪枕',29,10,9,[24,20,20,18],'48×74｜600克',productImages.pillow),single('P02','枕芯｜记忆棉枕',59,10,25,[42,38,38,35],'35×50｜600克',productImages.pillow),single('Q01','被芯｜奶酪被（2斤）',79,20,30,[59,55,55,52],'155×210｜2斤',productImages.duvet),single('Q02','被芯｜奶酪被（4斤）',99,20,40,[75,69,69,65],'155×210｜4斤',productImages.duvet),single('T01','三件套｜水洗棉',99,20,33,[65,59,59,55],'透气舒适的水洗棉三件套'),single('T02','三件套｜纯棉',149,30,65,[105,99,99,92],'亲肤耐用的纯棉三件套',productImages.cotton),single('M01','床垫｜小竹垫 6CM',139,30,65,[109,99,99,92],'90×200｜6CM｜20D4CM',productImages.mattress),single('M02','床垫｜小竹垫 8CM',179,30,85,[139,129,129,120],'90×200｜8CM｜20D6CM',productImages.mattress),single('M03','床垫｜小蓝垫 4CM',179,30,85,[139,129,129,120],'90×200｜4CM｜30D1CM+25D3CM',productImages.mattress),single('M04','床垫｜小蓝垫 6CM',219,30,110,[169,159,159,148],'90×200｜6CM｜30D2CM+25D4CM',productImages.mattress)];
let cart=[],chosenProduct,chosenStyle,quantity=1,currentFilter='全部';const $=s=>document.querySelector(s);const money=n=>`¥${n}`;
function visual(p,style=p.photo){return style?.url?`<img src="${style.url}" alt="${style.name}">`:`<div class="placeholder"><span>☁</span><i></i></div>`}
function productCard(p){return `<button class="product-card" onclick="detail('${p.id}')">${p.tag?`<em>${p.tag}</em>`:''}<div class="product-image">${visual(p)}</div><div><small>${p.type} · ${p.id}</small><h3>${p.name}</h3><p><b>${money(p.price)}</b><span>定金 ${money(p.deposit)}</span></p></div></button>`}
function showPage(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#'+page).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===page));if(page==='admin')admin('orders');window.scrollTo({top:0,behavior:'smooth'})}
function showCatalog(type){currentFilter=type;showPage('catalog');$('#catalogTitle').textContent=type==='全部'?'全部床品':type==='套餐'?'新生套餐':'单独选购';document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('#catalogProducts').innerHTML=products.filter(p=>type==='全部'||p.type===type).map(productCard).join('')}
function detail(id){chosenProduct=products.find(p=>p.id===id);chosenStyle=chosenProduct.styles[0];quantity=1;renderDetail();showPage('detail')}
function renderDetail(){const p=chosenProduct;$('#detailProduct').innerHTML=`<div class="detail-image">${visual(p,chosenStyle)}</div><article class="detail-copy"><p class="label">${p.type==='套餐'?'NEW STUDENT SET':'SINGLE ITEM'} · ${p.id}</p><h1>${p.name}</h1><p class="description">${p.desc}</p><div class="price-box"><span>学生专享价<b>${money(p.price)}</b></span><span>预订定金<b>${money(p.deposit)}</b></span></div><h4>选择花色</h4><div class="styles">${p.styles.map((s,i)=>`<button class="${s===chosenStyle?'selected':''}" onclick="chooseStyle(${i})">${s.name}</button>`).join('')}</div><div class="quantity"><b>数量</b><div><button onclick="changeQty(-1)">−</button><span>${quantity}</span><button onclick="changeQty(1)">+</button></div></div></article><div class="buybar"><button class="primary" onclick="addCart()">加入预订清单 <span>定金 ${money(p.deposit*quantity)}</span></button></div>`}
function chooseStyle(i){chosenStyle=chosenProduct.styles[i];renderDetail()}function changeQty(change){quantity=Math.max(1,quantity+change);renderDetail()}function addCart(){const found=cart.find(x=>x.id===chosenProduct.id&&x.style.name===chosenStyle.name);if(found)found.quantity+=quantity;else cart.push({...chosenProduct,style:chosenStyle,quantity});updateCart();toast('已加入预订清单');setTimeout(showCheckout,300)}
function updateCart(){$('#cartCount').textContent=cart.reduce((sum,x)=>sum+x.quantity,0)}function showCheckout(){if(!cart.length){toast('请先选择床品');return}const deposit=cart.reduce((sum,x)=>sum+x.deposit*x.quantity,0);$('#cartItems').innerHTML=cart.map(x=>`<div><span>${x.name}<small>${x.style.name} · ×${x.quantity}</small></span><b>${money(x.price*x.quantity)}</b></div>`).join('')+`<footer>应付定金 <b>${money(deposit)}</b></footer>`;$('#depositTotal').textContent=money(deposit);showPage('checkout')}
function submitOrder(event){event.preventDefault();$('#paymentAmount').textContent=$('#depositTotal').textContent;showPage('payment')}function receiptChosen(input){if(input.files[0]){$('#receiptText').textContent=`✓ 已选择：${input.files[0].name}`}}function confirmPayment(){if(!document.querySelector('.upload input').files[0])return toast('请先上传付款截图');toast('凭证已提交，负责人将尽快核验');setTimeout(()=>{cart=[];updateCart();showPage('home')},900)}
function admin(tab){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.textContent.includes(tab==='orders'?'订单':tab==='goods'?'商品':'代理')));if(tab==='orders')$('#adminPanel').innerHTML=`<section class="panel"><header><h3>待核验订单</h3><button>导出订单 ↓</button></header>${[['赵同学','水洗棉九件套｜小蓝垫','¥50'],['李同学','床垫｜小竹垫 6CM ×2','¥60'],['周同学','水洗棉六件套｜小竹垫','¥50']].map(x=>`<div class="order"><b>${x[0]} <em>待核验</em></b><small>${x[1]} · 定金 ${x[2]} · 北区 3 栋 503 室</small><button onclick="toast('演示：定金已核验')">核验定金</button></div>`).join('')}</section>`;else if(tab==='goods')$('#adminPanel').innerHTML=`<section class="panel"><header><h3>商品管理</h3><button>＋ 新增商品</button></header>${products.map(p=>`<div class="goods"><span>${visual(p)}</span><b>${p.name}<small>${p.id} · 定金 ${money(p.deposit)}</small></b><strong>${money(p.price)}</strong></div>`).join('')}</section>`;else $('#adminPanel').innerHTML=`<section class="panel"><header><h3>股东与二级代理</h3><button>＋ 新建代理</button></header>${[['陈同学','股东 · 旗下 6 名二级代理','¥8,942'],['王同学','二级代理 · 归属：陈同学 · 18 件/套','¥2,538'],['刘同学','二级代理 · 归属：陈同学 · 9 件/套','¥1,096']].map(x=>`<div class="agent"><i>${x[0][0]}</i><b>${x[0]}<small>${x[1]}</small></b><strong>${x[2]}</strong></div>`).join('')}</section>`}
function copyLink(){navigator.clipboard?.writeText(location.href+'?ref=wang-2026');toast('你的专属推广链接已复制')}let timer;function toast(text){clearTimeout(timer);const el=$('#toast');el.textContent=text;el.classList.add('on');timer=setTimeout(()=>el.classList.remove('on'),1800)}
$('#featuredProducts').innerHTML=products.filter(p=>p.type==='套餐').slice(0,4).map(productCard).join('');
