const db = window.supabase.createClient(window.SUPABASE_CONFIG.url, window.SUPABASE_CONFIG.publishableKey);
const $ = s => document.querySelector(s); const yuan = n => `¥${Number(n || 0).toLocaleString('zh-CN',{maximumFractionDigits:2})}`;
let dashboard, currentTab='shareholders';
async function boot(){const {data:{session}}=await db.auth.getSession();if(session) await loadAdmin();}
async function signIn(){const {error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)return message(error.message);await loadAdmin()}
async function signUpAdmin(){const {error}=await db.auth.signUp({email:$('#email').value.trim(),password:$('#password').value,options:{data:{name:'广职床品管理员'}}});if(error)return message(error.message);message('账号已创建，请查看邮箱验证；验证后再登录。')}
async function signOut(){await db.auth.signOut();location.reload()}
async function loadAdmin(){const {data:{user}}=await db.auth.getUser();const {data:profile,error}=await db.from('profiles').select('role').eq('id',user.id).single();if(error||profile?.role!=='admin'){await db.auth.signOut();return message('此账号不是管理员。请用 309175115@qq.com 注册后再登录。')}$('#login').hidden=true;$('#app').hidden=false;await refresh();}
async function refresh(){const {data,error}=await db.rpc('admin_dashboard');if(error)return toast('数据库还未初始化：请先运行 schema.sql');dashboard=data;renderSummary();tab(currentTab,document.querySelector(`nav button[onclick*="${currentTab}"]`));}
function renderSummary(){const s=dashboard.shareholders||[];$('#summary').innerHTML=`<div><small>股东总数</small><strong>${s.length}</strong><em>可在下方新增</em></div><div><small>三个股东套餐总销量</small><strong>${s.reduce((n,x)=>n+Number(x.package_units||0),0)} 套</strong><em>仅“尾款已收”订单计入</em></div><div><small>待处理</small><strong>${dashboard.pending_agents+dashboard.pending_orders}</strong><em>${dashboard.pending_agents} 个代理 · ${dashboard.pending_orders} 个订单</em></div>`}
function tab(name,button){currentTab=name;document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));button?.classList.add('active');if(name==='shareholders')renderShareholders();if(name==='agents')renderAgents();if(name==='orders')renderOrders();if(name==='settings')renderSettings();}
function renderShareholders(){const s=dashboard.shareholders||[];$('#panel').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>股东总览</h2><small>包含股东本人和旗下二级代理的已收尾款销售</small></div><button onclick="openShareholder()">＋ 新增股东</button></div><div class="shareholder-grid">${s.map(x=>`<article class="share-card"><h3>${x.name}</h3><small>套餐销量</small><b>${x.package_units} 套</b><small>学生销售额 ${yuan(x.sales)} · 股东收益 ${yuan(x.profit)}</small><code>${location.origin.replace('admin','')}?ref=${x.promotion_code}</code><button class="secondary" style="margin-top:9px" onclick="copy('${x.promotion_code}')">复制专属链接</button></article>`).join('')||'<p>还没有股东。请先新增“啊瀚、yy、赖狗狗”。</p>'}</div></div>`}
function openShareholder(){$('#panel').insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div><h3>新增股东</h3><label>姓名<input id="shareName" placeholder="例如：啊瀚"></label><label>手机号（可选）<input id="sharePhone"></label><label>微信号（可选）<input id="shareWechat"></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">取消</button><button onclick="createShareholder()">创建并生成链接</button></div></div></div>`)}function closeModal(){$('#modal')?.remove()}
async function createShareholder(){const {error}=await db.rpc('admin_create_shareholder',{p_name:$('#shareName').value.trim(),p_phone:$('#sharePhone').value.trim()||null,p_wechat:$('#shareWechat').value.trim()||null});if(error)return toast(error.message);closeModal();toast('股东已创建');await refresh()}
async function renderAgents(){const {data,error}=await db.from('agents').select('id,name,phone,wechat,role,status,shareholder_id,promotion_code,created_at,shareholder:shareholder_id(name)').order('created_at',{ascending:false});if(error)return toast(error.message);$('#panel').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>代理审核</h2><small>二级代理自行注册后，只有你审核通过才可获得推广链接。</small></div></div>${data.map(a=>`<div class="row"><div class="grow"><strong>${a.name}</strong> <span class="badge ${a.status==='active'?'active':''}">${a.status}</span><small>${a.role==='shareholder'?'股东':'二级代理'} · 推荐股东：${a.shareholder?.name||'—'} · ${a.phone||'未填手机号'} · ${a.wechat||'未填微信'}</small></div>${a.status==='pending'?`<button onclick="approve('${a.id}',true)">通过</button><button class="danger" onclick="approve('${a.id}',false)">拒绝</button>`:`<button class="secondary" onclick="copy('${a.promotion_code||''}')">复制链接</button>`}</div>`).join('')||'<p>暂无代理申请。</p>'}</div>`}
async function approve(id,ok){const {error}=await db.rpc('admin_approve_agent',{p_agent:id,p_approve:ok,p_notes:null});if(error)return toast(error.message);toast(ok?'代理已通过并生成链接':'已拒绝申请');await renderAgents();await refresh()}
async function renderOrders(){const {data,error}=await db.from('orders').select('id,order_no,customer_name,phone,building,room,status,retail_total,deposit_total,balance_due,refund_amount,refund_reason,created_at,agent:promotion_agent_id(name)').order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message);$('#panel').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>订单与退款</h2><small>只有标为“尾款已收”才计入销量和收益；退款会自动扣回并重算。</small></div></div>${data.map(o=>`<div class="row"><div class="grow"><strong>${o.order_no} · ${o.customer_name}</strong> <span class="badge ${o.status==='paid'?'active':''}">${o.status}</span><small>${o.building} ${o.room} · ${o.agent?.name||'自然流量'} · 总价 ${yuan(o.retail_total)} · 定金 ${yuan(o.deposit_total)} · 尾款 ${yuan(o.balance_due)}</small></div>${o.status!=='paid'&&o.status!=='refunded'?`<button onclick="status('${o.id}','paid')">确认尾款</button>`:''}${o.status==='paid'?`<button class="danger" onclick="refund('${o.id}')">退款</button>`:''}</div>`).join('')||'<p>暂无订单。学生商城接入后，订单会出现在这里。</p>'}</div>`}
async function status(id,value){const {error}=await db.rpc('admin_update_order',{p_order:id,p_status:value,p_refund_amount:null,p_refund_reason:null});if(error)return toast(error.message);toast('订单已更新，收益已重算');await renderOrders();await refresh()}
function refund(id){const reason=prompt('退款原因（必填）：');if(!reason)return;const amount=Number(prompt('退款金额：'));if(!Number.isFinite(amount))return toast('退款金额无效');db.rpc('admin_update_order',{p_order:id,p_status:'refunded',p_refund_amount:amount,p_refund_reason:reason}).then(async({error})=>{if(error)return toast(error.message);toast('退款已标注，收益已重算');await renderOrders();await refresh()})}
async function renderSettings(){const {data,error}=await db.from('settlement_periods').select('*').order('starts_on',{ascending:false});if(error)return toast(error.message);$('#panel').innerHTML=`<div class="panel"><div class="panel-head"><div><h2>结算周期</h2><small>二级代理按整个周期“已收尾款套餐”最终数量统一重算阶梯；单卖不计阶梯销量。</small></div></div>${data.map(p=>`<div class="row"><div class="grow"><strong>${p.name}</strong><small>${p.starts_on} 至 ${p.ends_on} · ${p.status}</small></div><button class="secondary" onclick="recalc('${p.id}')">重新计算</button></div>`).join('')}</div>`}
async function recalc(id){const {error}=await db.rpc('recalculate_period',{p_period:id});if(error)return toast(error.message);toast('已按最终套餐销量重新计算');await refresh()}
function copy(code){if(!code)return toast('尚未生成推广链接');const link=`${location.origin}/gz-bedding/?ref=${code}`;navigator.clipboard?.writeText(link);toast('专属学生商城链接已复制')}
function toast(t){const e=$('#toast');e.textContent=t;e.style.display='block';clearTimeout(window.tt);window.tt=setTimeout(()=>e.style.display='none',2400)}function message(t){$('#loginMessage').textContent=t}
boot();
